### ISSUE TITLE
Milestone 1 - Test coverage and improvements for release

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-go#36]
**Feature description**

Improve test coverage for features implemented in `master`.

**Is your feature request related to a problem? Please describe.**
For some time skycoin/hardware-wallet#28 has been blocking tests from running in headless mode after CLI invocation.

**Describe the solution you'd like**
- [x] Ensure all commands have a level of testing suitable for releasing Milestone 1 .
- [x] Checkout skycoin/hardware-wallet
- [x] Build emulator and run it in the background
- ~Instrument the test suite to press emulator buttons automatically~ see #75 
- [x] Test against emulator in Travis CI
- ~README . Explain versioning contract . Best practices for libraries . Basic dev setup .~ see skycoin/hardware-wallet#64
- [x] Development guidelines in README
- [x] Improve Makefile
- [x] Update changelog to reflect changes in project history
- [x] Add `devRemovePin` function to send `ChangePin` message with `remove=1`

**Comment by olemis** [comment]
depends on #75

**Comment by stdevAlDen** [comment]
> **Feature description**
> 
> Improve test coverage for features implemented in `master`.
> 
> **Is your feature request related to a problem? Please describe.**
> For some time [skycoin/hardware-wallet#28](https://github.com/skycoin/hardware-wallet/issues/28) has been blocking tests from running in headless mode after CLI invocation.
> 
> **Describe the solution you'd like**
> 
> * [ ]  Ensure all commands have a level of testing suitable for releasing Milestone 1 .
> * [x]  Checkout skycoin/hardware-wallet
> * [x]  Build emulator and run it in the background
> * Instrument the test suite to press emulator buttons automatically see #75
> * [x]  Test against emulator in Travis CI
> * README . Explain versioning contract . Best practices for libraries . Basic dev setup . see [skycoin/hardware-wallet#64](https://github.com/skycoin/hardware-wallet/issues/64)
> * [x]  Development guidelines in README
> * [x]  Improve Makefile
> * [x]  Update changelog to reflect changes in project history

@olemis an important feature from end user manual is the:
1- generate mnemonic
2- backup device
3- recovery seed
workflow, this can not be tested now because when you see a message (recovering the device)  in the device screen like:
"Enter the first word", this information is not sended thought the protocol, so making an integration test for this it's not posible right now.

**Comment by olemis** [comment]
@stdevAlDen why not ?

**Comment by stdevAlDen** [comment]
> @stdevAlDen why not ?

@olemis [This is](https://github.com/skycoin/hardware-wallet-protob/blob/a54547e49d38cd9b2b9a9ff10334099322e17ba2/protob/messages/messages.proto#L410-L412) how are currently designed, the software need to be designed to be tested (modified in our case) right?.
